### ISSUE TITLE
Adding advanced "commands"

### ISSUE THREAD

**Issue by ostcrom** [ianlucas/mathjax-editor#30]
Hello there, I have been tinkering with mathjax-editor for a couple weeks and I am trying to improve it to meet the needs of my own project. 

The current task I am working on is getting the integral symbol to work with the corresponding subscript and superscript numbers. In LaTeX this should look like:
`\int_a^b`

For testing/tinker purposes I bind it to a button like so in the buttons definitions using the sample index.html:
`'\\int': function (editor) { editor.insert('\\int_{a}^{b}' ) }`

This works somewhat, I get an integral symbol as expected but the 'a' is not subscript, it's normal and the 'b' is superscript to the 'a'.

When I inspect the HTML, I think I see the problem:
`<script type="math/tex" id="MathJax-Element-1">\int{\;a\;}^{b}{\cursor}</script>`

As you can see my latex has been altered a little:
`\int_{\;a\;}^{b}`

I have been digging around, it seems like this might have something to do with the escapedCharacters constant but I am a bit of a js novice and frankly I'm stumped. Any clues on how to get the integral symbol to work correctly?

**Comment by ianlucas** [comment]
Hi there!

The way the editor works with Latex is very tricky. It needs to follow some patterns I've made. This could've been improved with a proper Latex parser (that I intend to do the next month). So, to get the expression "\int{a}^{b}" to work, you should add a whitespace after "\int", like this: "\int {a}^{b}", then it should work (I mean, kind of, since the cursor placement is quite bugged, I gonna get into this).

The whitespace is needed because the dumb way I parse Latex requires that commands without blocks (like \alpha, \beta, and \int) to have a whitespace after it, so "\int ".

At the moment my computer is broken, so I expect to get it fixed until the end of the month so I can look at some stuff on the code of this project.

**Comment by ostcrom** [comment]
Thanks for taking the time to explain. I was studying the code some more and I see what you mean about the parser and the cursor placement. It is clever but perhaps overly 'tricky' as you put it :) . I think parsing straight tex would simplify things as well, and I am going to take a stab at rejiggering the parsing. I would be pleasantly surprised if I come up with anything better than your effort however ;) .

At any rate, cheers on your work so far! I think if you improve the parsing and cursor like you mentioned then this package will be really stellar.

**Comment by ostcrom** [comment]
Doing some more research on this, sounds like anyone trying to parse TeX will have their cut out for them:
https://tex.stackexchange.com/questions/4201/is-there-a-bnf-grammar-of-the-tex-language

**Comment by ostcrom** [comment]
Still doing some more research, it might be much easier to have the editor write in MathML. MathML even has a js DOM already:
https://www.w3.org/TR/MathML2/chapter8.html

Looks like MathJax should also be able to convert MathML back to TeX if that is needed for some reason. I will post back if I have any luck with this approach.

**Comment by pkra** [comment]
Some random comments.

* Don't try to write your own TeX parser. Since TeX is [Type-0 but not Type-1](https://en.wikipedia.org/wiki/Chomsky_hierarchy#Type-0_grammars), essentially, only TeX can parse TeX. 
* For an editor, you should be able to write a restricted grammar (e.g., you won't need macros, just a set of building blocks). Still, you shouldn't write your own; maybe look at MediaWiki's texvc (and check their visual editor while you're at it). If you need more, look at MathJax's parser.
* Since MathJax uses something very close to MathML as an internal format, writing a MathML editor is in fact more natural but most people prefer TeX. But likely you will end up using a custom format, at which point you might try to generate TeX from it (cf. MathQuill).
*  MathJax cannot convert MathML to TeX. Generally speaking, you cannot convert MathML to human-readable TeX; but again a restricted syntax can help.

**Comment by ianlucas** [comment]
So I finally got a new laptop and now I can get back to work on this project.

I will read the comments on this thread and hopefully I will join the discussion on how to improve the editor!

**Comment by ianlucas** [comment]
I created a new issue to discuss a rewrite of the editor. #32
